"""initial schema

Revision ID: cad789423a98
Revises: 
Create Date: 2026-06-15 13:42:47.709029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cad789423a98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('sub_topic', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_high_priority', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'week', 'sub_topic', name='uq_syllabus_row')
    )
    op.create_index('ix_syllabus_month_week', 'syllabus_tracker', ['month', 'week'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('daily_hours_goal', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reminder_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_tg_user_id'), 'user_profile', ['tg_user_id'], unique=True)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookmarks_user_created', 'bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theory_done', sa.Boolean(), nullable=False),
    sa.Column('pyq_done', sa.Boolean(), nullable=False),
    sa.Column('aptitude_done', sa.Boolean(), nullable=False),
    sa.Column('hours_studied', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_log')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_logs')
    op.drop_index('ix_bookmarks_user_created', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_user_profile_tg_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('ix_syllabus_month_week', table_name='syllabus_tracker')
    op.drop_table('syllabus_tracker')
    # ### end Alembic commands ###
